name: dart_tags
description: The library for work with music tags like ID3. Written on pure Dart. It can be used in flutter, web, and vm projects.
version: 0.3.1
homepage: https://github.com/NiKoTron/dart-tags

environment:
  sdk: '>=2.3.0 <3.0.0' 

dependencies:
  utf: ^0.9.0+5
  collection: ^1.14.13
  convert: ^2.1.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
